### PR TITLE
add gradlew and make setting up the workspace automated

### PR DESCRIPTION
**Pull request by coehlrich**
this will make it so that people can just run gradlew setupDecompWorkspace and gradlew eclipse or idea without having to download all the dependencies themselves.

### CODE REVIEW

**Comment by coehlrich** [comment]
i have already started working on making it compatible with whatever mods the user has installed

**Comment by andrewminer** [comment]
Thanks for doing this!  I admit that I'm a complete novice when it comes to making Minecraft mods, and I'm grateful for the assistance!  In fact, I don't really have more than a vague idea of what I'm doing here.  A few questions for you:

  * Why do you need a shell script to run `gradle`?  Why not use the `gradle` command directly?
  * Am I correct that you left a bunch of the files in place because they aren't available in maven?
  * Each time I want to add support for a new mod, how do I figure out if the needed files exist in maven?

**Comment by coehlrich** [comment]
im not completely sure but every tutorial i have seen gets them to run the gradlew command
and for the second question that is correct (i tried to use [jitpack](https://jitpack.io/) but they wouldnt compile
and for the third question although jitpack has how to do it for jitpack and curseforge has it in one of their docs if you want to use a regular maven like this one http://chickenbones.net/maven/ in the repositries you would put
`maven { url = http://chickenbones.net/maven/ }`  and replace the chicken bones maven with the one you want or if its already in repositries you dont need to do anything with it and in the dependencies lets say you wanted to add not enough items dev version 1.0.5.120 for 1.7.10 you would add
`compile "codechicken:NotEnoughItems:1.7.10-1.0.5.120:dev"` which adds not enough items dev to eclipse and you dont actually need the mods in the mods folder in minecraft because they are loaded in minecraft when you start it from eclipse or idea.

**Comment by coehlrich** [comment]
also i will be testing the code in my versions with a modpack that has over 200 mods.

**Comment by andrewminer** [comment]
Heh.  That should be interesting.  Bear in mind, though, that this mod hasn't gotten any love from me for a while now, and I'm not sure how compatible the data format it creates will be with what the site now uses.  I don't recall whether I ever got around to updating the mod to match.

**Comment by coehlrich** [comment]
i also just really want to use this mod with the site

**Comment by coehlrich** [comment]
i do see some functions for the oredictionary.

**Comment by andrewminer** [comment]
So far, I've deliberately not tried to use that data on the site to keep things simple for the crafting algorithm it uses.  I'm not opposed to collecting it in the data, but it doesn't currently have much use.

**Pull request merged**
